spring.application.name=distributed-message-broker
server.port=${SERVER_PORT:8082}

# PostgreSQL DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mqdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Password123!}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
mq.data.dir=${MQ_DATA_DIR:/tmp/mq-data}

broker.id=${BROKER_ID:broker-1}
broker.host=${BROKER_HOST:localhost}
broker.port=${server.port}



# All peers in the cluster (every broker lists ALL addresses including its own -
# BrokerStartupConfig will exclude self automatically)
cluster.peers=${CLUSTER_PEERS:localhost:8082,localhost:8083,localhost:8084}

# Replication settings
replication.factor=3
replication.timeout.ms=5000

retention.hours=168
retention.max.bytes=1073741824
retention.check.interval.ms=300000